version: "3.9"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: primetrade_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./charts:/app/charts
      - ./outputs:/app/outputs
      - ./notebooks:/app/notebooks
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: primetrade_pipeline
    volumes:
      - ./data:/app/data
      - ./charts:/app/charts
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
    command: python run_pipeline.py
    profiles:
      - pipeline
